version: '3.5'
services:
  zebeat:
    hostname: "customer${ZE_CUSTOMER_NAME:-zebrium}_zebeat"
    image: "zebrium/zebeat:latest"
    privileged: true
    restart: "${DOCKER_RESTART_POLICY}"
    volumes:
      - ${PWD}/config:/config
      - ${PWD}/access_tokens.yml:/access_tokens.yml